version: '2'
services:
    ooooooooo-app:
        image: ooooooooo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ooooooooo-mysql:3306/ooooooooo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ooooooooo-mysql:
        extends:
            file: mysql.yml
            service: ooooooooo-mysql
